import React from 'react';
import {BrowserRouter, Navigate, Route, Routes} from 'react-router-dom';
import './App.css';
import HomePage from './pages/HomePage';
import LoginPage from './pages/auth/LoginPage';
import AppLayout from './components/layout/AppLayout';
import OperatorsPage from './pages/operators/OperatorsPage';
import TrainingHistoryPage from './pages/operators/TrainingHistoryPage';
import TasksPage from './pages/tasks/TasksPage';
import SettingsPage from './pages/settings/SettingsPage';
import ReportsPage from './pages/reports/ReportsPage';
import RegistrationPage from './pages/auth/RegistrationPage';
import ForgotPasswordPage from './pages/auth/ForgotPasswordPage';
import ResetPasswordPage from './pages/auth/ResetPasswordPage';
import AuthLayout from './components/layout/AuthLayout';
import ProtectedRoute from './components/auth/ProtectedRoute';
import MyAccountPage from './pages/account/MyAccountPage';
import VerifyEmailPage from './pages/auth/VerifyEmailPage';
import { PreferencesProvider } from '../context/preferences/PreferencesContext';
import { AccountProvider } from './context/AccountContext';
import RoleSetupComponent from '../components/managers/RoleSetupComponent';
import RoleDebugComponent from '../components/managers/RoleDebugComponent';
